### ISSUE TITLE
Release v0.30.0 selfhosted. Can't connect to name-based routes

### ISSUE THREAD

**Issue by deniritech** [netbirdio/netbird#2728]
**Describe the problem**

We updated our coordinator and peers to v0.30.0 and not we can not connect on the routes have setup.
We are selfhosting netbird. The issue happens when we move to version v0.30.1 as well.

**To Reproduce**

1. Update the coordinator.
2. Updated the peers.
3. Updated client locally.
4. We're unable to connect to DNS routes after selecting them.
The client log locally repeats the following:
```
2024-10-11T15:22:33+02:00 INFO client/internal/routemanager/client.go:171: New chosen route is ***REDACTED ROUTE*** with peer ***REDACTED PEER*** with score 0.000000 for network [***REDACTED NETWORK***]
2024-10-11T15:22:33+02:00 WARN client/internal/routemanager/client.go:130: peer ***REDACTED PEER*** has 0 latency
2024-10-11T15:22:38+02:00 WARN client/internal/routemanager/client.go:130: peer ***REDACTED PEER*** has 0 latency
2024-10-11T15:22:51+02:00 WARN client/internal/routemanager/client.go:130: peer ***REDACTED PEER*** has 0 latency
2024-10-11T15:23:03+02:00 INFO [peer: ***REDACTED PEER***] client/internal/peer/worker_relay.go:187: WireGuard handshake timed out, closing relay connection: 1970-01-01 01:00:00 +0100 CET
2024-10-11T15:23:03+02:00 INFO [relay: rel://***REDACTED COORDINATOR DOMAIN***:7777] relay/client/client.go:501: free up connection to peer: ***REDACTED***
2024-10-11T15:23:03+02:00 ERRO client/internal/wgproxy/usp/proxy.go:133: failed to read from remote conn: rel://***REDACTED COORDINATOR DOMAIN***:7777, EOF
2024-10-11T15:23:03+02:00 WARN client/internal/wgproxy/usp/proxy.go:122: error in proxy to local loop: 1 error occurred:
	* remote conn: connection already closed
2024-10-11T15:23:03+02:00 WARN client/internal/routemanager/client.go:160: The network [***REDACTED NETWORK***] has not been assigned a routing peer as no peers from the list [***REDACTED PEER***] are currently connected
2024-10-11T15:23:04+02:00 INFO [relay: rel://***REDACTED COORDINATOR DOMAIN***:7777] relay/client/client.go:214: open connection to peer: ***REDACTED***
2024-10-11T15:23:04+02:00 INFO [peer: ***REDACTED PEER***] client/internal/peer/conn.go:547: created new wgProxy for relay connection: 127.0.0.1:53261
2024-10-11T15:23:04+02:00 INFO [peer: ***REDACTED PEER***] client/internal/peer/conn.go:588: start to communicate with peer via relay
2024-10-11T15:23:04+02:00 WARN client/internal/routemanager/client.go:130: peer ***REDACTED PEER*** has 0 latency
2024-10-11T15:23:04+02:00 INFO client/internal/routemanager/client.go:171: New chosen route is ***REDACTED ROUTE*** with peer ***REDACTED PEER*** with score 0.000000 for network [***REDACTED NETWORK***]
2024-10-11T15:23:04+02:00 WARN client/internal/routemanager/client.go:130: peer ***REDACTED PEER*** has 0 latency
2024-10-11T15:23:11+02:00 WARN client/internal/routemanager/client.go:130: peer ***REDACTED PEER*** has 0 latency
2024-10-11T15:23:27+02:00 WARN client/internal/routemanager/client.go:130: peer ***REDACTED PEER*** has 0 latency
```

**Expected behavior**

We expected to be able to connect the the DNS route without an issue in this new release. When we roll back to v0.29.4 everything works.

**Are you using NetBird Cloud?**

We are using Self Hosted Netbird.

**NetBird version**

```
➜ netbird version
0.30.0
```

**NetBird status -dA output:**

In this case we can not add the status but for the route we want to use the peer is shown as connected. After we reload the page or try to connect to the page that DNS route links to it shows disconnected momentarily.

**Do you face any (non-mobile) client issues?**

Please provide the file created by `netbird debug for 1m -AS`.
We advise reviewing the anonymized files for any remaining PII.

**Screenshots**

**Additional context**

What we notice is the following :
1: We get connected to the peer we want: ``` New chosen route is XXXXXXXXX with peer XXXXXXXXX with score 0.000000 for network [XXXXXXXX]```
2: Error happens: ``` 2024-10-11T15:23:03+02:00 ERRO client/internal/wgproxy/usp/proxy.go:133: failed to read from remote conn: rel://*********:7777, EOF
2024-10-11T15:23:03+02:00 WARN client/internal/wgproxy/usp/proxy.go:122: error in proxy to local loop: 1 error occurred:
	* remote conn: connection already closed
2024-10-11T15:23:03+02:00 WARN client/internal/routemanager/client.go:160: The network [***********] has not been assigned a routing peer as no peers from the list [***************] are currently connected
2024-10-11T15:23:04+02:00 INFO [relay: rel://****************:7777] relay/client/client.go:214: open connection to peer: ********
2024-10-11T15:23:04+02:00 INFO [peer: ***********] client/internal/peer/conn.go:547: created new wgProxy for relay connection: 127.0.0.1:53261```
3: The peer gets assigned again. ```2024-10-11T15:23:03+02:00 WARN client/internal/routemanager/client.go:160: The network [XXXXXXXX] has not been assigned a routing peer as no peers from the list [XXXXXXXXXXX] are currently connected```
4: This repeats every time we want to connect to the same DNS route.
5: The same issue happens when we update to v0.30.1 as well.

**Comment by deniritech** [comment]
Fixed on 0.30.2
